database:
  host: app-db  #localhost #  # #
  port: 5432
  user: postgres
  password: 1234
  dbname: postgres

server:
  port: 8085

auth:
  secret_key: "fardinabir"
  expiry:
    access_token: 2
    refresh_token: 4

services:
  warden:
    host: http://warden #localhost #
    port: 8081
redis:
  host: redis #localhost #
  port: 6379
#  password: "redispw"